/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as SlugKitRouteImport } from './routes/$slug.kit'
import { Route as AuthenticatedCartaoUsuariosRouteImport } from './routes/_authenticated/cartao.usuarios'
import { Route as AuthenticatedCartaoTutoriaisRouteImport } from './routes/_authenticated/cartao.tutoriais'
import { Route as AuthenticatedCartaoTemaRouteImport } from './routes/_authenticated/cartao.tema'
import { Route as AuthenticatedCartaoImportarRouteImport } from './routes/_authenticated/cartao.importar'
import { Route as AuthenticatedCartaoFotoPerfilRouteImport } from './routes/_authenticated/cartao.foto-perfil'
import { Route as AuthenticatedCartaoFluxoRouteImport } from './routes/_authenticated/cartao.fluxo'
import { Route as AuthenticatedCartaoDashboardRouteImport } from './routes/_authenticated/cartao.dashboard'
import { Route as AuthenticatedCartaoConfiguracoesRouteImport } from './routes/_authenticated/cartao.configuracoes'
import { Route as AuthenticatedCartaoCartaoFisicoRouteImport } from './routes/_authenticated/cartao.cartao-fisico'
import { Route as AuthenticatedCartaoAssinaturaRouteImport } from './routes/_authenticated/cartao.assinatura'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugKitRoute = SlugKitRouteImport.update({
  id: '/$slug/kit',
  path: '/$slug/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCartaoUsuariosRoute =
  AuthenticatedCartaoUsuariosRouteImport.update({
    id: '/cartao/usuarios',
    path: '/cartao/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCartaoTutoriaisRoute =
  AuthenticatedCartaoTutoriaisRouteImport.update({
    id: '/cartao/tutoriais',
    path: '/cartao/tutoriais',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCartaoTemaRoute = AuthenticatedCartaoTemaRouteImport.update({
  id: '/cartao/tema',
  path: '/cartao/tema',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCartaoImportarRoute =
  AuthenticatedCartaoImportarRouteImport.update({
    id: '/cartao/importar',
    path: '/cartao/importar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCartaoFotoPerfilRoute =
  AuthenticatedCartaoFotoPerfilRouteImport.update({
    id: '/cartao/foto-perfil',
    path: '/cartao/foto-perfil',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCartaoFluxoRoute =
  AuthenticatedCartaoFluxoRouteImport.update({
    id: '/cartao/fluxo',
    path: '/cartao/fluxo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCartaoDashboardRoute =
  AuthenticatedCartaoDashboardRouteImport.update({
    id: '/cartao/dashboard',
    path: '/cartao/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCartaoConfiguracoesRoute =
  AuthenticatedCartaoConfiguracoesRouteImport.update({
    id: '/cartao/configuracoes',
    path: '/cartao/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCartaoCartaoFisicoRoute =
  AuthenticatedCartaoCartaoFisicoRouteImport.update({
    id: '/cartao/cartao-fisico',
    path: '/cartao/cartao-fisico',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCartaoAssinaturaRoute =
  AuthenticatedCartaoAssinaturaRouteImport.update({
    id: '/cartao/assinatura',
    path: '/cartao/assinatura',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$slug/kit': typeof SlugKitRoute
  '/$slug/': typeof SlugIndexRoute
  '/cartao/assinatura': typeof AuthenticatedCartaoAssinaturaRoute
  '/cartao/cartao-fisico': typeof AuthenticatedCartaoCartaoFisicoRoute
  '/cartao/configuracoes': typeof AuthenticatedCartaoConfiguracoesRoute
  '/cartao/dashboard': typeof AuthenticatedCartaoDashboardRoute
  '/cartao/fluxo': typeof AuthenticatedCartaoFluxoRoute
  '/cartao/foto-perfil': typeof AuthenticatedCartaoFotoPerfilRoute
  '/cartao/importar': typeof AuthenticatedCartaoImportarRoute
  '/cartao/tema': typeof AuthenticatedCartaoTemaRoute
  '/cartao/tutoriais': typeof AuthenticatedCartaoTutoriaisRoute
  '/cartao/usuarios': typeof AuthenticatedCartaoUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$slug/kit': typeof SlugKitRoute
  '/$slug': typeof SlugIndexRoute
  '/cartao/assinatura': typeof AuthenticatedCartaoAssinaturaRoute
  '/cartao/cartao-fisico': typeof AuthenticatedCartaoCartaoFisicoRoute
  '/cartao/configuracoes': typeof AuthenticatedCartaoConfiguracoesRoute
  '/cartao/dashboard': typeof AuthenticatedCartaoDashboardRoute
  '/cartao/fluxo': typeof AuthenticatedCartaoFluxoRoute
  '/cartao/foto-perfil': typeof AuthenticatedCartaoFotoPerfilRoute
  '/cartao/importar': typeof AuthenticatedCartaoImportarRoute
  '/cartao/tema': typeof AuthenticatedCartaoTemaRoute
  '/cartao/tutoriais': typeof AuthenticatedCartaoTutoriaisRoute
  '/cartao/usuarios': typeof AuthenticatedCartaoUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/$slug/kit': typeof SlugKitRoute
  '/$slug/': typeof SlugIndexRoute
  '/_authenticated/cartao/assinatura': typeof AuthenticatedCartaoAssinaturaRoute
  '/_authenticated/cartao/cartao-fisico': typeof AuthenticatedCartaoCartaoFisicoRoute
  '/_authenticated/cartao/configuracoes': typeof AuthenticatedCartaoConfiguracoesRoute
  '/_authenticated/cartao/dashboard': typeof AuthenticatedCartaoDashboardRoute
  '/_authenticated/cartao/fluxo': typeof AuthenticatedCartaoFluxoRoute
  '/_authenticated/cartao/foto-perfil': typeof AuthenticatedCartaoFotoPerfilRoute
  '/_authenticated/cartao/importar': typeof AuthenticatedCartaoImportarRoute
  '/_authenticated/cartao/tema': typeof AuthenticatedCartaoTemaRoute
  '/_authenticated/cartao/tutoriais': typeof AuthenticatedCartaoTutoriaisRoute
  '/_authenticated/cartao/usuarios': typeof AuthenticatedCartaoUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$slug/kit'
    | '/$slug/'
    | '/cartao/assinatura'
    | '/cartao/cartao-fisico'
    | '/cartao/configuracoes'
    | '/cartao/dashboard'
    | '/cartao/fluxo'
    | '/cartao/foto-perfil'
    | '/cartao/importar'
    | '/cartao/tema'
    | '/cartao/tutoriais'
    | '/cartao/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$slug/kit'
    | '/$slug'
    | '/cartao/assinatura'
    | '/cartao/cartao-fisico'
    | '/cartao/configuracoes'
    | '/cartao/dashboard'
    | '/cartao/fluxo'
    | '/cartao/foto-perfil'
    | '/cartao/importar'
    | '/cartao/tema'
    | '/cartao/tutoriais'
    | '/cartao/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/$slug/kit'
    | '/$slug/'
    | '/_authenticated/cartao/assinatura'
    | '/_authenticated/cartao/cartao-fisico'
    | '/_authenticated/cartao/configuracoes'
    | '/_authenticated/cartao/dashboard'
    | '/_authenticated/cartao/fluxo'
    | '/_authenticated/cartao/foto-perfil'
    | '/_authenticated/cartao/importar'
    | '/_authenticated/cartao/tema'
    | '/_authenticated/cartao/tutoriais'
    | '/_authenticated/cartao/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SlugKitRoute: typeof SlugKitRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/kit': {
      id: '/$slug/kit'
      path: '/$slug/kit'
      fullPath: '/$slug/kit'
      preLoaderRoute: typeof SlugKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cartao/usuarios': {
      id: '/_authenticated/cartao/usuarios'
      path: '/cartao/usuarios'
      fullPath: '/cartao/usuarios'
      preLoaderRoute: typeof AuthenticatedCartaoUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cartao/tutoriais': {
      id: '/_authenticated/cartao/tutoriais'
      path: '/cartao/tutoriais'
      fullPath: '/cartao/tutoriais'
      preLoaderRoute: typeof AuthenticatedCartaoTutoriaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cartao/tema': {
      id: '/_authenticated/cartao/tema'
      path: '/cartao/tema'
      fullPath: '/cartao/tema'
      preLoaderRoute: typeof AuthenticatedCartaoTemaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cartao/importar': {
      id: '/_authenticated/cartao/importar'
      path: '/cartao/importar'
      fullPath: '/cartao/importar'
      preLoaderRoute: typeof AuthenticatedCartaoImportarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cartao/foto-perfil': {
      id: '/_authenticated/cartao/foto-perfil'
      path: '/cartao/foto-perfil'
      fullPath: '/cartao/foto-perfil'
      preLoaderRoute: typeof AuthenticatedCartaoFotoPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cartao/fluxo': {
      id: '/_authenticated/cartao/fluxo'
      path: '/cartao/fluxo'
      fullPath: '/cartao/fluxo'
      preLoaderRoute: typeof AuthenticatedCartaoFluxoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cartao/dashboard': {
      id: '/_authenticated/cartao/dashboard'
      path: '/cartao/dashboard'
      fullPath: '/cartao/dashboard'
      preLoaderRoute: typeof AuthenticatedCartaoDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cartao/configuracoes': {
      id: '/_authenticated/cartao/configuracoes'
      path: '/cartao/configuracoes'
      fullPath: '/cartao/configuracoes'
      preLoaderRoute: typeof AuthenticatedCartaoConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cartao/cartao-fisico': {
      id: '/_authenticated/cartao/cartao-fisico'
      path: '/cartao/cartao-fisico'
      fullPath: '/cartao/cartao-fisico'
      preLoaderRoute: typeof AuthenticatedCartaoCartaoFisicoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cartao/assinatura': {
      id: '/_authenticated/cartao/assinatura'
      path: '/cartao/assinatura'
      fullPath: '/cartao/assinatura'
      preLoaderRoute: typeof AuthenticatedCartaoAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCartaoAssinaturaRoute: typeof AuthenticatedCartaoAssinaturaRoute
  AuthenticatedCartaoCartaoFisicoRoute: typeof AuthenticatedCartaoCartaoFisicoRoute
  AuthenticatedCartaoConfiguracoesRoute: typeof AuthenticatedCartaoConfiguracoesRoute
  AuthenticatedCartaoDashboardRoute: typeof AuthenticatedCartaoDashboardRoute
  AuthenticatedCartaoFluxoRoute: typeof AuthenticatedCartaoFluxoRoute
  AuthenticatedCartaoFotoPerfilRoute: typeof AuthenticatedCartaoFotoPerfilRoute
  AuthenticatedCartaoImportarRoute: typeof AuthenticatedCartaoImportarRoute
  AuthenticatedCartaoTemaRoute: typeof AuthenticatedCartaoTemaRoute
  AuthenticatedCartaoTutoriaisRoute: typeof AuthenticatedCartaoTutoriaisRoute
  AuthenticatedCartaoUsuariosRoute: typeof AuthenticatedCartaoUsuariosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCartaoAssinaturaRoute: AuthenticatedCartaoAssinaturaRoute,
  AuthenticatedCartaoCartaoFisicoRoute: AuthenticatedCartaoCartaoFisicoRoute,
  AuthenticatedCartaoConfiguracoesRoute: AuthenticatedCartaoConfiguracoesRoute,
  AuthenticatedCartaoDashboardRoute: AuthenticatedCartaoDashboardRoute,
  AuthenticatedCartaoFluxoRoute: AuthenticatedCartaoFluxoRoute,
  AuthenticatedCartaoFotoPerfilRoute: AuthenticatedCartaoFotoPerfilRoute,
  AuthenticatedCartaoImportarRoute: AuthenticatedCartaoImportarRoute,
  AuthenticatedCartaoTemaRoute: AuthenticatedCartaoTemaRoute,
  AuthenticatedCartaoTutoriaisRoute: AuthenticatedCartaoTutoriaisRoute,
  AuthenticatedCartaoUsuariosRoute: AuthenticatedCartaoUsuariosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SlugKitRoute: SlugKitRoute,
  SlugIndexRoute: SlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
